name: Download and Commit Template

on:
  workflow_dispatch:

jobs:
  download_template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Debug: Show git remote, status, and config
        run: |
          echo "===> Git remote:"
          git remote -v
          echo "===> Git status:"
          git status
          echo "===> Git config:"
          git config --list

      - name: Download template from Azure DevOps
        run: |
          # Simulate template download (replace with your actual curl or script)
          echo "# Example workflow" > .github/workflows/name.yml

      - name: Debug: Git status after download
        run: git status

      - name: Commit and push changes using PAT
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git add .github/workflows/name.yml
            git commit -m "Auto-update: downloaded template from Azure DevOps"
            echo "===> Attempting push with PAT_TOKEN"
            git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }} HEAD:main
          else
            echo "===> No changes to commit"
          fi
