name: Download and Commit Template

on:
  workflow_dispatch:

jobs:
  download_template:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allows actions to modify repository contents
      workflow: write  # Allows actions to modify workflow files

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Download template from Azure DevOps
      - name: Download template from Azure DevOps
        run: |
          mkdir -p .github/workflows
          curl -u :${{ secrets.AZURE_DEVOPS_TOKEN }} \
            -H "Accept: application/octet-stream" \
            -L \
            "https://dev.azure.com/senarindam/Payel%20Bose/_apis/git/repositories/Jfrog/items?path=/github/workflows/name.yml&api-version=7.0" \
            -o .github/workflows/name.yml

      # Step 3: Configure Git for PAT push
      - name: Configure Git for PAT push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          # Set the GitHub repo URL using the PAT token
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}

      # Step 4: Commit and push changes if any
      - name: Commit downloaded template
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git add .github/workflows/name.yml
            git commit -m "Auto-update: downloaded template from Azure DevOps"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi

      # Step 5: Trigger template-execution workflow
      - name: Trigger template-execution workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-template-execution
