name: Download and Commit Template

on:
  workflow_dispatch:

permissions:
  contents: write      # allow committing files
  workflows: write     # allow modifying workflows (.github/workflows/*.yml)

jobs:
  download_template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download template from Azure DevOps
        run: |
          mkdir -p .github/workflows
          curl -u :${{ secrets.AZURE_DEVOPS_TOKEN }} \
            -H "Accept: application/octet-stream" \
            -L \
            "https://dev.azure.com/senarindam/Payel%20Bose/_apis/git/repositories/Jfrog/items?path=/github/workflows/name.yml&api-version=7.0" \
            -o .github/workflows/name.yml

      - name: Commit downloaded template
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          if [[ -n $(git status --porcelain) ]]; then
            git add .github/workflows/name.yml
            git commit -m "Auto-update: downloaded template from Azure DevOps"
            git push
          else
            echo "No changes to commit"
          fi

      - name: Trigger template-execution workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-template-execution
