name: Print My Name

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Enter your name'
        required: true
        default: 'Payel'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Name
        run: echo "Hello, my name is ${{ github.event.inputs.username }}"
