name: Call Template from Azure DevOps

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Enter your name'
        required: true
        default: 'Payel'

jobs:
  print-name:
    runs-on: ubuntu-latest

    steps:
      - name: Set up credentials for Azure DevOps
        run: |
          echo "https://:${{ secrets.AZURE_DEVOPS_TOKEN }}@dev.azure.com" > ~/.git-credentials
          git config --global credential.helper store

      - name: Clone Azure DevOps repository
        run: |
          git clone https://${{ secrets.AZURE_DEVOPS_TOKEN }}@dev.azure.com/senarindam/Payel%20Bose/_git/Jfrog
          cd Jfrog
          git checkout main

      - name: Print the name (simulate template behavior)
        run: echo "Hello, my name is ${{ github.event.inputs.username }}"
